/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cpeactivity;

import javax.swing.JTextField;

/**
 *
 * @author Asus
 */
public class activity1 extends javax.swing.JFrame {

    /**
     * Creates new form activity1
     */
    public activity1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFname = new javax.swing.JLabel();
        jLabelLname = new javax.swing.JLabel();
        jLabelMname = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        middleName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        finalsGrade = new javax.swing.JTextField();
        Remark = new javax.swing.JTextField();
        midtermGrade = new javax.swing.JTextField();
        fieldName = new javax.swing.JTextField();
        prelimGrade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        quizPrelims = new javax.swing.JTextField();
        quizMidterms = new javax.swing.JTextField();
        quizFinals = new javax.swing.JTextField();
        attendancePrelims = new javax.swing.JTextField();
        attendanceMidterms = new javax.swing.JTextField();
        attendanceFinals = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        examPrelims = new javax.swing.JTextField();
        examMidterms = new javax.swing.JTextField();
        examFinals = new javax.swing.JTextField();
        projectPrelims = new javax.swing.JTextField();
        projectMidterms = new javax.swing.JTextField();
        projectFinals = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelFname.setText("First Name:");

        jLabelLname.setText("Last Name:");

        jLabelMname.setText("Middle Name:");

        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });

        middleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleNameActionPerformed(evt);
            }
        });

        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Midterm Grade:");

        jLabel2.setText("Name of Student:");

        jLabel3.setText("Prelim Grade:");

        jLabel4.setText("Finals Grade:");

        jLabel5.setText("Remarks: ");

        finalsGrade.setEditable(false);

        Remark.setEditable(false);
        Remark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemarkActionPerformed(evt);
            }
        });

        midtermGrade.setEditable(false);
        midtermGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midtermGradeActionPerformed(evt);
            }
        });

        fieldName.setEditable(false);
        fieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameActionPerformed(evt);
            }
        });

        prelimGrade.setEditable(false);
        prelimGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prelimGradeActionPerformed(evt);
            }
        });

        jLabel6.setText("Attendance (5%)");

        quizPrelims.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizPrelimsActionPerformed(evt);
            }
        });
        quizPrelims.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quizPrelimsKeyPressed(evt);
            }
        });

        quizMidterms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizMidtermsActionPerformed(evt);
            }
        });
        quizMidterms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quizMidtermsKeyPressed(evt);
            }
        });

        quizFinals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizFinalsActionPerformed(evt);
            }
        });
        quizFinals.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quizFinalsKeyPressed(evt);
            }
        });

        attendancePrelims.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendancePrelimsActionPerformed(evt);
            }
        });
        attendancePrelims.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                attendancePrelimsKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                attendancePrelimsKeyTyped(evt);
            }
        });

        attendanceMidterms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceMidtermsActionPerformed(evt);
            }
        });
        attendanceMidterms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                attendanceMidtermsKeyPressed(evt);
            }
        });

        attendanceFinals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceFinalsActionPerformed(evt);
            }
        });
        attendanceFinals.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                attendanceFinalsKeyPressed(evt);
            }
        });

        jLabel7.setText("Prelims");

        jLabel8.setText("Finals");

        jLabel9.setText("Midterms");

        jLabel11.setText("Quiz (40%)");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Exam (30%)");

        examPrelims.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examPrelimsActionPerformed(evt);
            }
        });
        examPrelims.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                examPrelimsKeyPressed(evt);
            }
        });

        examMidterms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examMidtermsActionPerformed(evt);
            }
        });
        examMidterms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                examMidtermsKeyPressed(evt);
            }
        });

        examFinals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examFinalsActionPerformed(evt);
            }
        });
        examFinals.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                examFinalsKeyPressed(evt);
            }
        });

        projectPrelims.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectPrelimsActionPerformed(evt);
            }
        });
        projectPrelims.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                projectPrelimsKeyPressed(evt);
            }
        });

        projectMidterms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectMidtermsActionPerformed(evt);
            }
        });
        projectMidterms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                projectMidtermsKeyPressed(evt);
            }
        });

        projectFinals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectFinalsActionPerformed(evt);
            }
        });
        projectFinals.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                projectFinalsKeyPressed(evt);
            }
        });

        jLabel10.setText("Project (25%)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFname, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMname, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLname, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(middleName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(midtermGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel8))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(attendanceFinals, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(attendancePrelims, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(attendanceMidterms, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(19, 19, 19))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(31, 31, 31)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(quizFinals, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(quizPrelims, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(quizMidterms, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(jLabel11)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(projectFinals, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(projectPrelims, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(projectMidterms, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10)
                                                .addGap(35, 35, 35)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(examFinals, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(examPrelims, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(examMidterms, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(jLabel13))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(fieldName, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(prelimGrade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Remark, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(finalsGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1)))
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(44, 44, 44))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFname)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMname)
                    .addComponent(middleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLname)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quizPrelims, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quizMidterms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quizFinals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(attendancePrelims, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(attendanceMidterms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(attendanceFinals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(examPrelims, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(examMidterms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(examFinals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(projectPrelims, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(projectMidterms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(projectFinals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(prelimGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(midtermGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finalsGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Remark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void middleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameActionPerformed

    private void RemarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemarkActionPerformed

    private void midtermGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midtermGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midtermGradeActionPerformed

    private void prelimGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prelimGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prelimGradeActionPerformed

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void quizPrelimsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizPrelimsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quizPrelimsActionPerformed

    private void quizMidtermsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizMidtermsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quizMidtermsActionPerformed

    private void quizFinalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizFinalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quizFinalsActionPerformed

    private void attendancePrelimsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendancePrelimsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attendancePrelimsActionPerformed
        
    private void attendanceMidtermsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceMidtermsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attendanceMidtermsActionPerformed

    private void attendanceFinalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceFinalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attendanceFinalsActionPerformed

    private void examPrelimsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examPrelimsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_examPrelimsActionPerformed

    private void examMidtermsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examMidtermsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_examMidtermsActionPerformed

    private void examFinalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examFinalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_examFinalsActionPerformed

    private void projectPrelimsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectPrelimsActionPerformed
        // TODO add your handling code here:
        String text = projectPrelims.getText();
        try {
            int value = Integer.parseInt(text);
            if (value < 65 || value > 100) {
                projectPrelims.setText("");
            }
        } catch (NumberFormatException ex) {
            projectPrelims.setText("");
        }
    }//GEN-LAST:event_projectPrelimsActionPerformed

    private void projectMidtermsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectMidtermsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectMidtermsActionPerformed

    private void projectFinalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectFinalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectFinalsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        firstName.setText("");
        middleName.setText("");
        lastName.setText("");
        
        attendancePrelims.setText("");
        quizPrelims.setText("");
        projectPrelims.setText("");
        examPrelims.setText("");
        attendanceMidterms.setText("");
        quizMidterms.setText("");
        projectMidterms.setText("");
        examMidterms.setText("");
        attendanceFinals.setText("");
        quizFinals.setText("");
        projectFinals.setText("");
        examFinals.setText("");
        
        fieldName.setText("");
        prelimGrade.setText("");
        midtermGrade.setText("");
        finalsGrade.setText("");
        Remark.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameActionPerformed

    private void attendancePrelimsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_attendancePrelimsKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_attendancePrelimsKeyTyped

    private void attendancePrelimsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_attendancePrelimsKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            attendancePrelims.setEditable(false);
        }else{
            attendancePrelims.setEditable(true);
        }    
    }//GEN-LAST:event_attendancePrelimsKeyPressed

    private void attendanceMidtermsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_attendanceMidtermsKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            attendanceMidterms.setEditable(false);
        }else{
            attendanceMidterms.setEditable(true);
        }
    }//GEN-LAST:event_attendanceMidtermsKeyPressed

    private void attendanceFinalsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_attendanceFinalsKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            attendanceFinals.setEditable(false);
        }else{
            attendanceFinals.setEditable(true);
        }
    }//GEN-LAST:event_attendanceFinalsKeyPressed

    private void quizPrelimsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quizPrelimsKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            quizPrelims.setEditable(false);
        }else{
            quizPrelims.setEditable(true);
        }
    }//GEN-LAST:event_quizPrelimsKeyPressed

    private void quizMidtermsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quizMidtermsKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            quizMidterms.setEditable(false);
        }else{
            quizMidterms.setEditable(true);
        }
    }//GEN-LAST:event_quizMidtermsKeyPressed

    private void quizFinalsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quizFinalsKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            quizFinals.setEditable(false);
        }else{
            quizFinals.setEditable(true);
        }
    }//GEN-LAST:event_quizFinalsKeyPressed

    private void projectPrelimsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_projectPrelimsKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            projectPrelims.setEditable(false);
        }else{
            projectPrelims.setEditable(true);
        }
    }//GEN-LAST:event_projectPrelimsKeyPressed

    private void projectMidtermsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_projectMidtermsKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            projectMidterms.setEditable(false);
        }else{
            projectMidterms.setEditable(true);
        }
    }//GEN-LAST:event_projectMidtermsKeyPressed

    private void projectFinalsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_projectFinalsKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            projectFinals.setEditable(false);
        }else{
            projectFinals.setEditable(true);
        }
    }//GEN-LAST:event_projectFinalsKeyPressed

    private void examPrelimsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_examPrelimsKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            examPrelims.setEditable(false);
        }else{
            examPrelims.setEditable(true);
        }
    }//GEN-LAST:event_examPrelimsKeyPressed

    private void examMidtermsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_examMidtermsKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            examMidterms.setEditable(false);
        }else{
            examMidterms.setEditable(true);
        }
    }//GEN-LAST:event_examMidtermsKeyPressed

    private void examFinalsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_examFinalsKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            examFinals.setEditable(false);
        }else{
            examFinals.setEditable(true);
        }
    }//GEN-LAST:event_examFinalsKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String fName = firstName.getText();
        String mName = middleName.getText();
        String lName = lastName.getText();
        String fdName = fName + " " + mName + " " + lName;
        fieldName.setText(fdName);
 
    try {
    //scores from text fields for prelims
    double attendancePrelimsScore = Double.parseDouble(attendancePrelims.getText());
    double quizPrelimsScore = Double.parseDouble(quizPrelims.getText());
    double projectPrelimsScore = Double.parseDouble(projectPrelims.getText());
    double examPrelimsScore = Double.parseDouble(examPrelims.getText());

    // to calculate the prelim grade using a weighted average (adjust weights as needed)
    double prelimGrade1 = (attendancePrelimsScore + quizPrelimsScore + projectPrelimsScore + examPrelimsScore) / 4;
    
    prelimGrade.setText("" + prelimGrade1);

    //scores from text fields for midterms
    double attendanceMidtermsScore = Double.parseDouble(attendanceMidterms.getText());
    double quizMidtermsScore = Double.parseDouble(quizMidterms.getText());
    double projectMidtermsScore = Double.parseDouble(projectMidterms.getText());
    double examMidtermsScore = Double.parseDouble(examMidterms.getText());

    // to calculate the midterm grade using a weighted average (adjust weights as needed)
    double midtermGrade1 = (attendanceMidtermsScore + quizMidtermsScore + projectMidtermsScore + examMidtermsScore) / 4;
    
    midtermGrade.setText("" + midtermGrade1);
    
    

    //scores from text fields for finals
    double attendanceFinalsScore = Double.parseDouble(attendanceFinals.getText());
    double quizFinalsScore = Double.parseDouble(quizFinals.getText());
    double projectFinalsScore = Double.parseDouble(projectFinals.getText());
    double examFinalsScore = Double.parseDouble(examFinals.getText());

    // to calculate the finals grade
    double finalsGrade1 = (attendanceFinalsScore + quizFinalsScore + projectFinalsScore + examFinalsScore) / 4;

    // to calculate the overall grade by averagingmidterm, and finals grades
    double finalsGrade2 = (midtermGrade1 + finalsGrade1) / 2;

    // to display the calculated overall grade in a label
    finalsGrade.setText("" + finalsGrade2);
    
     String remarks = (finalsGrade2 >= 75) ? "Pass" : "Fail";

    Remark.setText("" + remarks);
} catch (NumberFormatException e) {
    finalsGrade.setText("");
}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(activity1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(activity1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(activity1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(activity1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new activity1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Remark;
    private javax.swing.JTextField attendanceFinals;
    private javax.swing.JTextField attendanceMidterms;
    private javax.swing.JTextField attendancePrelims;
    private javax.swing.JTextField examFinals;
    private javax.swing.JTextField examMidterms;
    private javax.swing.JTextField examPrelims;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField finalsGrade;
    private javax.swing.JTextField firstName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFname;
    private javax.swing.JLabel jLabelLname;
    private javax.swing.JLabel jLabelMname;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField middleName;
    private javax.swing.JTextField midtermGrade;
    private javax.swing.JTextField prelimGrade;
    private javax.swing.JTextField projectFinals;
    private javax.swing.JTextField projectMidterms;
    private javax.swing.JTextField projectPrelims;
    private javax.swing.JTextField quizFinals;
    private javax.swing.JTextField quizMidterms;
    private javax.swing.JTextField quizPrelims;
    // End of variables declaration//GEN-END:variables
}
